### ISSUE TITLE
Custom fields not saving

### ISSUE THREAD

**Issue by Jaimer** [asikart/userxtd#21]
I have 95 registered users in my joomla 3.3.4 site and now i noticed that only 19 have information saved for the custom fields I created with UserXTD. And only those 19 user_id's appear in the profiles table in the database.

I just did a test myself creating a user account and none info was saved without showing any kind of error.

**Comment by amg2nd** [comment]
The native profile plugin works fine in Joomla 3.3.6. I think there might be an issue with the code in the current userXTD plugin. It was working before except for the fact that when looking at the 'UserXTD > Users' page it would only display one page with no page navigation visible. Then I upgraded using the Joomla Extension Manager. Now there is page navigation, but the extra fields will not save and it still shows that the component needs updated in the Extension Manager

**Comment by kubanc** [comment]
Hello,
I have downloaded version 1.0.0 and installed it on Joomla 3.3.6. When user makes the registration none of the information in the custom fields created with userxtd is saved.

but as I found out, in the back end on Joomla if I edit custom fields for specific user, the information is then saved.

**Comment by MagisterBoBBer** [comment]
Yeah, I know. But that makes no sense. I've lost all useful information about my users and they wont reenter it. Total disappointment. Thanks for your reply. I've decided to not fix the plugin and installed another.
