### ISSUE TITLE
Clicking on a user in backend opens a new tab in Firefox

### ISSUE THREAD

**Issue by jjsjjs** [asikart/userxtd#24]
Hi, like the title says. When clicking on a user in the back-end, then it is not opened in the same windows (this window gets only white) but opens in a new tab in Firefox.

**Comment by asika32764** [comment]
Yes, it is not a but. UserXTD will jump to core user manager, so it open a new tab that will not confuse users between these two components.

**Comment by jjsjjs** [comment]
ok, that is confusing, because you expect the component to take over the 
functionality, so you can leave the core component at rest.

Simon Asika schreef op 11-3-2015 om 17:12:

**Comment by asika32764** [comment]
Core component is large, it will not so easy to replace whole com_users

But I think I can add some tips to notice users that the links will jump to
com_users

jjsjjs <notifications@github.com> 於 2015年3月12日 星期四寫道：

> ok, that is confusing, because you expect the component to take over the
> functionality, so you can leave the core component at rest.
>
> Simon Asika schreef op 11-3-2015 om 17:12:
> >
> > Yes, it is not a but. UserXTD will jump to core user manager, so it
> > open a new tab that will not confuse users between these two components.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/asikart/userxtd/issues/24#issuecomment-78295744>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asikart/userxtd/issues/24#issuecomment-78336241>.
>


-- 
Best Regard

Simon Asika | Kwang Po Tung | 董冠伯
------------------------------------------------
- Founder: Asikart Extension <http://ext.asikart.com/>
- CTO: SMS Taiwan <http://www.bm-sms.com.tw/>

- Mobile: 886-928-565-747
- Github: https://github.com/asika32764

**Comment by jjsjjs** [comment]
Ok, good. Thanks!

Simon Asika schreef op 11-3-2015 om 19:27:
