### ISSUE TITLE
Key JLanguage has not been registered with the container.

### ISSUE THREAD

**Issue by Akhanto** [asikart/userxtd#29]
I just installed this extension but I fail to open and use it. 
I get the error above.

**Comment by ehsanasgari** [comment]
me too...

**Comment by asika32764** [comment]
Please install new Windwalker library to fix this issue.
https://github.com/ventoviro/windwalker-joomla-rad/releases/download/2.0.10/windwalker-rad-2.0.10.zip

We'll release a new version of UserXTD soon.

**Comment by Akhanto** [comment]
Just did it and reinstalled userxtd. Same error :/

**Comment by asika32764** [comment]
Don't reinstall userxtd, you should only unzip windwalker to libraries.

**Comment by Akhanto** [comment]
Anyways I did it. It still doesn't work.

**Comment by asika32764** [comment]
Install UserXTD first, this is the error message.

![p-2015-04-04-4](https://cloud.githubusercontent.com/assets/1639206/6992838/ceb9f44a-db12-11e4-8d9a-4b636a7e5ec1.jpg)

Download Windwalker patch file, unzip it and replace the origin one.

![p-2015-04-04-5](https://cloud.githubusercontent.com/assets/1639206/6992837/ceb748e4-db12-11e4-81d8-ebbdfb7b012d.jpg)

Now UseXTD should work.

![p-2015-04-04-6](https://cloud.githubusercontent.com/assets/1639206/6992836/ceb5bdf8-db12-11e4-8677-94564dcd4048.jpg)

**Comment by Akhanto** [comment]
works great. Thank you

**Comment by asika32764** [comment]
[1.0.2](https://github.com/asikart/userxtd/releases/tag/1.0.2) has available.
