### ISSUE TITLE
Removing of fields not possible

### ISSUE THREAD

**Issue by Akhanto** [asikart/userxtd#30]
Hey. Now I can open the control panel of userxtd but I can't delete any fields. It says 
"Message
12 items successfully trashed"
but everything is still there.

**Comment by asika32764** [comment]
I can confirm this problem, please wait for our next release.

**Comment by asika32764** [comment]
Should be fixed in [1.0.2](https://github.com/asikart/userxtd/releases/tag/1.0.2).
